version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - pip
            - -r requirements.txt
      - run:
          name: Run Bot
          command: python Moin.py

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      
