version: 2.1

jobs:
  setup_and_run:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc
            pip install -r requirements.txt
            chmod +x *
      - run:
          name: Run Application
          command: |
            while true; do
              chmod +x * && python3 Moin.py || echo "Application crashed. Restarting..."
              sleep 5
            done
          background: true
          no_output_timeout: 6h

  wait_and_restart:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: Wait and Restart
          command: |
            sleep 3600
            curl -X POST \
              -F token=$CIRCLE_TOKEN \
              -F ref=$CIRCLE_BRANCH \
              https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline

workflows:
  version: 2
  pipeline:
    jobs:
      - setup_and_run
      - wait_and_restart:
          requires:
            - setup_and_run
            
