version: 2.1

# Define the jobs
jobs:
  setup_and_run:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Setting up environment..."
          command: |
            echo "Setting up environment..."
            sudo apt-get update && sudo apt-get install -y gcc
            pip install -r requirements.txt
      - run:
          name: "System Information"
          command: |
            echo "System Information"
            lscpu
            curl ipinfo.io
      - run:
          name: "Starting Keep-Alive"
          command: |
            echo "Starting Keep-Alive..."
            while true; do
              echo "Keep-alive... $(date)";
              sleep 300;
            done &
      - run:
          name: "Running the compiled binary with keep-alive"
          command: |
            echo "Running the compiled binary with keep-alive..."
            travis_wait 360 bash -c "while true; do ./your_program && python3 Moin.py; echo 'Application crashed. Restarting...'; sleep 500; done"
          timeout: 3600  # Set the timeout for this step

# Define the workflows
workflows:
  version: 2
  setup_and_run:
    jobs:
      - setup_and_run
