version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install python-telegram-bot asyncio
      - run:
          name: Run Telegram Bot
          command: python RAHUL.py

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      
      
