version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install pyTelegramBotAPI pymongo certifi
      - run:
          name: Run Bot
          command: |
           python Moin.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      
